server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/student/**
  application:
    name: Gateway 